Converting-Controllers-from-Query-builder-to-ORM
aanish27/employee-profile-manager pull request #95
Opened 2024-10-31 16:48 UTC by aanish27

#93 PR Created please review @Raza9798

2024-10-31 17:05 UTC, Raza9798 commented
only the relationship fields are ordering and other columns are not ordering please fix it

2024-10-31 17:09 UTC, aanish27 commented
> only the relationship fields are ordering and other columns are not ordering please fix it


Yes fixed #95 please review again

2024-10-31 21:39 UTC, Raza9798 requested changes

2024-10-31 21:39 UTC, Raza9798 commented on app/Http/Controllers/CompanyController.php
> -        if (!is_null($request->query('order'))) {
fix the filer dropdown

2024-11-14 15:02 UTC, Raza9798 approved these changes

2024-11-14 15:02 UTC, merged